### ISSUE TITLE
Questions about CUDA version 

### ISSUE THREAD

**Issue by jihwankwak** [zhangchbin/RCIL#10]
First of all, thank you for sharing your work.
I have several questions about reproducing your code and code from PLOP, which you have referred.

Q1. Have you also worked on CUDA 10.2?
Official code of MiB and PLOP works on CUDA 10.2. And I might have missed it, but there is no CUDA description on your github repo. Since the code also relies on 'apex' package, I guess it's also working on CUDA10.2. Have you worked on CUDA 10.2? 

Q2. Have you tried to reproduce it on CUDA > 11.0 
It may not be true but I figured out that 'apex' package can be installed on CUDA version under 11.0.
As far as I know, for CUDA version higher than 11.0, torch.cuda.amp is used instead
So I have tried to update the code from PLOP without apex package using amp module from torch.cuda. But, currently, I am also facing some error with 'inplace-abn' package. So I was just wondering if you have tried reproducing the code on higher version of CUDA.

**Comment by schuy1er** [comment]
Hi, thanks for reaching out. 
For Q1, if you mean cudatoolkit, we tried that and it should work. But I think it's not a problem. Try it first and ask me again if you have any problems. 
For Q2, since inplace-abn restrict the cuda version, we didn't try on cuda > 11.0. Nevertheless, it should be noticed that inplace-abn is a little bit different from the normal bn layer(In dealing with minimal terms). Based on this, our transformation has also changed a bit. If you replace inplace-abn with syncbn, remember to fix this part.
`gamma = bn2d.weight.abs() + eps
    beta = bn2d.bias`

**Comment by zhangchbin** [comment]
Hi, @jihwankwak Thanks for your interest.
We have updated the conda environment requirements in the repository. We run all experiments on Python3.6 + Torch1.3.1 + CUDA 10.1 and installed Apex from source code.

**Comment by jihwankwak** [comment]
First of all, thank @schuy1er @zhangchbin for fast reply.

For @schuy1er, 
Yes, the code works perfectly on your descriptions. 
As you might have noticed in Q2, I have been wondering how to update this PLOP code framework in higher CUDA version. 
Since I am having trouble doing this, this led me to ask the CUDA version of your implementation, since your code is also based on PLOP framework.
I will try to replace inplace-abn with syncbn, as you suggested. This may help me out. Thank you again.

Thanks @zhangchbin for your fast update.

**Comment by zhangchbin** [comment]
hi, @jihwankwak 
We found that high version pytorch can not reach the supposed performance due to the bug caused by InplaceABNSync, which has been fixed in our latest commitment. You can refer to our latest news. Sorry for the inconvenience caused.

**Comment by jihwankwak** [comment]
Thanks for letting me know.
I haven't check the code yet, but I will let you know if I bump into another questions.
By the way, have you tried to implement basic baselines such as MiB, PLOP in the higher version as well?
For me, those results are quite different than codes based on CUDA10.2.


-----Original Message-----
