### ISSUE TITLE
About data augmentation

### ISSUE THREAD

**Issue by laibao-ai** [zhangchbin/RCIL#2]
Really great work, I would like to ask how this method works if it is just pure data augmentation instead of class augmentation

**Comment by zhangchbin** [comment]
Hi, @Totorol 
In this work, we apply two settings, continual class segmentation and continual domain segmentation. For continual domain segmentation, we assume there are the same classes in different domain. Positively, I think you can try this method on the incremental data.

**Comment by laibao-ai** [comment]
> 
非常感谢
