### ISSUE TITLE
ade script

### ISSUE THREAD

**Issue by wwwwyw** [zhangchbin/RCIL#3]
复现ade场景有些问题，请问能公开一下ade数据集的脚本吗

**Comment by schuy1er** [comment]
抱歉迟到的回复！因为暑假和疫情原因还没有回实验室 : ( 我们会在回去的第一时间整理出来发出，非常抱歉！关于ade的问题，主要是蒸馏的强度，你可能需要调整一下里面的参数，这个我有在另外一个问题里回答，你可以看一下

**Comment by zhangchbin** [comment]
@wwwwyw 
Hi, I'm sorry for the late reply. We have fixed bugs in the repository, and you can find the re-implemented results on VOC and ADE20K. If there is any questions, please feel easy to let us know.
Thanks for your help.
