### ISSUE TITLE
Full Results on ADE20k

### ISSUE THREAD

**Issue by Ze-Yang** [zhangchbin/RCIL#6]
Hi, may I have the class-wise results for ADE20k? Thanks.

**Comment by schuy1er** [comment]
uhhhhh sorry but I don't have the log right now since I'm not in the lab, so please wait for a few days. I will send them to you as soon as possible.

**Comment by Ze-Yang** [comment]
May I know the value for `--loss_kd` on different settings of ADE20k?

**Comment by schuy1er** [comment]
Just try 100 for it, and let me know if it doesn't work.

**Comment by zhangchbin** [comment]
Hi @Ze-Yang
@schuy1er 
I'm sorry for the late reply. We have fixed bugs in the repository, and you can find the re-implemented results on VOC and ADE20K. If there is any questions, please feel easy to let us know.
Thanks for your help.
